const BACK_PLATE = "PBAK";
const FACE = "PGHE";
const FACEMASK = "PFMK";
const FIRST_NAME = "PFNA";
const HAND_WARMER = "PLHW";
const ID = "PRSI";
const JERSEY_SLEEVES = "PJER";
const LAST_NAME = "PLNA";
const LEFT_ANKLE = "PSPL";
const LEFT_BICEP = "PLBB";
const LEFT_CALF = "PLCB";
const LEFT_ELBOW = "PLEL";
const LEFT_FOREARM = "PLFB";
const LEFT_HAND = "PLHA";
const LEFT_KNEE = "PLKN";
const LEFT_SLEEVE = "PLSL";
const LEFT_WRIST = "PLWR";
const POSITION = "PPOS";
const RIGHT_ANKLE = "PSPR";
const RIGHT_BICEP = "PRBB";
const RIGHT_CALF = "PRCB";
const RIGHT_ELBOW = "PREL";
const RIGHT_FOREARM = "PRFB";
const RIGHT_HAND = "PRHA";
const RIGHT_KNEE = "PRKN";
const RIGHT_SLEEVE = "PLSR";
const RIGHT_WRIST = "PRWR";
const SHELL = "PHLM";
const TOWEL = "PLTW";
const VISOR = "PVIS";
const WEIGHT = "PWGT";

module.exports = {
	BACK_PLATE,
	FACE,
	FACEMASK,
	FIRST_NAME,
	HAND_WARMER,
	ID,
	JERSEY_SLEEVES,
	LAST_NAME,
	LEFT_ANKLE,
	LEFT_BICEP,
	LEFT_CALF,
	LEFT_ELBOW,
	LEFT_FOREARM,
	LEFT_HAND,
	LEFT_KNEE,
	LEFT_SLEEVE,
	LEFT_WRIST,
	POSITION,
	RIGHT_BICEP,
	RIGHT_ANKLE,
	RIGHT_CALF,
	RIGHT_ELBOW,
	RIGHT_FOREARM,
	RIGHT_HAND,
	RIGHT_KNEE,
	RIGHT_SLEEVE,
	RIGHT_WRIST,
	SHELL,
	TOWEL,
	VISOR,
	WEIGHT,
};
