const NIKE = 1;
const UNDER_ARMOUR = 2;
const OAKLEY = 3;
const DARK_NIKE = 4;
const DARK_UNDER_ARMOUR = 5;
const DARK_OAKLEY = 6;

module.exports = { NIKE, UNDER_ARMOUR, OAKLEY, DARK_NIKE, DARK_UNDER_ARMOUR, DARK_OAKLEY };
