const HELMETS = require("../../../../../../../../constants/ea-mappings/players/equipment/helmets");

const skilledPositions = [
	{ type: HELMETS.STANDARD_TWO_BAR, weight: 1 },
	{ type: HELMETS.STANDARD_THREE_BAR, weight: 1 },
	{ type: HELMETS.STANDARD_ROBOT_RB, weight: 1 },
	{ type: HELMETS.STANDARD_KICKER, weight: 1 },
	{ type: HELMETS.STANDARD_ROBOT, weight: 1 },
	{ type: HELMETS.STANDARD_THREE_BAR_RB, weight: 1 },
	{ type: HELMETS.STANDARD_THREE_BAR_RB_JAGGED, weight: 1 },
	{ type: HELMETS.AIR_XP_TWO_BAR, weight: 1 },
	{ type: HELMETS.AIR_XP_THREE_BAR, weight: 1 },
	{ type: HELMETS.AIR_XP_ROBOT_RB, weight: 1 },
	{ type: HELMETS.AIR_XP_KICKER, weight: 1 },
	{ type: HELMETS.AIR_XP_ROBOT, weight: 1 },
	{ type: HELMETS.AIR_XP_THREE_BAR_RB, weight: 1 },
	{ type: HELMETS.AIR_XP_THREE_BAR_RB_JAGGED, weight: 1 },
	{ type: HELMETS.SCHUTT_TWO_BAR, weight: 1 },
	{ type: HELMETS.SCHUTT_THREE_BAR, weight: 1 },
	{ type: HELMETS.SCHUTT_ROBOT_RB, weight: 1 },
	{ type: HELMETS.SCHUTT_KICKER, weight: 1 },
	{ type: HELMETS.SCHUTT_ROBOT, weight: 1 },
	{ type: HELMETS.SCHUTT_THREE_BAR_RB, weight: 1 },
	{ type: HELMETS.SCHUTT_THREE_BAR_RB_JAGGED, weight: 1 },
	{ type: HELMETS.DNA_DNA_5, weight: 1 },
	{ type: HELMETS.DNA_DNA_6, weight: 1 },
	{ type: HELMETS.DNA_DNA_ROPO_SW, weight: 1 },
	{ type: HELMETS.DNA_DNA_ROPO_SW_2, weight: 1 },
	{ type: HELMETS.REVO_SPEED_SPEED_ROBOT, weight: 1 },
	{ type: HELMETS.REVO_SPEED_SPEED_ROBOT_2, weight: 1 },
	{ type: HELMETS.REVO_SPEED_SPEED_3_BAR_RB, weight: 1 },
	{ type: HELMETS.REVO_SPEED_SPEED_3_BAR_LB, weight: 1 },
	{ type: HELMETS.REVO_SPEED_SPEED_3_BAR, weight: 1 },
	{ type: HELMETS.ION_4D_ION_2_BAR, weight: 1 },
	{ type: HELMETS.ION_4D_ION_ROBOT_RB, weight: 1 },
	{ type: HELMETS.ION_4D_ION_3_BAR_RB, weight: 1 },
	{ type: HELMETS.ION_4D_ION_3_BAR, weight: 1 },
];

module.exports = skilledPositions;
