const NORMAL = 0;
const NIKE_VAPOR_FLY = 3;
const UNDER_ARMOUR_NITRO = 4;
const GENERIC_GLOVE = 7;
const ADIDAS_ADIZERO = 10;
const OL = 13;
const TAPED_FINGERS_WHITE = 15;
const TAPED_FINGERS_TEAM_COLOR = 17;
const TAPED_HAND = 18;
const TAPED_HAND_MAX = 19;
const TAPED_HAND_COMBO = 20;

module.exports = {
	NORMAL,
	NIKE_VAPOR_FLY,
	UNDER_ARMOUR_NITRO,
	GENERIC_GLOVE,
	ADIDAS_ADIZERO,
	OL,
	TAPED_FINGERS_WHITE,
	TAPED_FINGERS_TEAM_COLOR,
	TAPED_HAND,
	TAPED_HAND_MAX,
	TAPED_HAND_COMBO,
};
