const SHORT = 0;
const LONG_WHITE = 1;
const LONG_TEAM_COLOR = 3;
const BTM_HALF_SLEEVE_WHITE = 4;
const BTM_HALF_SLEEVE_TEAM_COLOR = 6;
const TOP_HALF_SLEEVE_WHITE = 7;
const TOP_HALF_SLEEVE_TEAM_COLOR = 9;
const THREE_QUARTERS_SLEEVE_WHITE = 10;
const THREE_QUARTERS_SLEEVE_TEAM_COLOR = 12;

module.exports = {
	SHORT,
	LONG_WHITE,
	LONG_TEAM_COLOR,
	BTM_HALF_SLEEVE_WHITE,
	BTM_HALF_SLEEVE_TEAM_COLOR,
	TOP_HALF_SLEEVE_WHITE,
	TOP_HALF_SLEEVE_TEAM_COLOR,
	THREE_QUARTERS_SLEEVE_WHITE,
	THREE_QUARTERS_SLEEVE_TEAM_COLOR,
};
