const NORMAL = 0;
const ELBOW_PAD_WHITE = 1;
const ELBOW_PAD_TEAM_COLOR = 3;
const ELBOW_PAD_WHITE_STRIPE = 4;
const RUBBER_PAD = 7;
const SWEATBAND_FULL_WHITE = 8;
const SWEATBAND_MED_WHITE = 9;
const SWEATBAND_THIN_WHITE = 10;
const SWEATBAND_FULL_TEAM_COLOR = 14;
const SWEATBAND_MED_TEAM_COLOR = 15;
const SWEATBAND_THIN_TEAM_COLOR = 16;
const ELBOW_BRACE_TEAM_COLOR = 17;
const ELBOW_GUARD = 18;

module.exports = {
	NORMAL,
	ELBOW_PAD_WHITE,
	ELBOW_PAD_TEAM_COLOR,
	ELBOW_PAD_WHITE_STRIPE,
	RUBBER_PAD,
	SWEATBAND_FULL_WHITE,
	SWEATBAND_MED_WHITE,
	SWEATBAND_THIN_WHITE,
	SWEATBAND_FULL_TEAM_COLOR,
	SWEATBAND_MED_TEAM_COLOR,
	SWEATBAND_THIN_TEAM_COLOR,
	ELBOW_BRACE_TEAM_COLOR,
	ELBOW_GUARD,
};
