const HELMETS = require("../../../../../../../../constants/ea-mappings/players/equipment/helmets");

const oLinePositions = [
	{ type: HELMETS.STANDARD_TWO_BAR, weight: 0.5 },
	{ type: HELMETS.STANDARD_THREE_BAR, weight: 0.5 },
	{ type: HELMETS.STANDARD_FULL_CAGE_1, weight: 1 },
	{ type: HELMETS.STANDARD_HALF_CAGE_1, weight: 0.1 },
	{ type: HELMETS.STANDARD_ROBOT_RB, weight: 0.5 },
	{ type: HELMETS.STANDARD_KICKER, weight: 0.5 },
	{ type: HELMETS.STANDARD_ROBOT, weight: 0.5 },
	{ type: HELMETS.STANDARD_THREE_BAR_RB, weight: 0.5 },
	{ type: HELMETS.STANDARD_THREE_BAR_RB_JAGGED, weight: 0.5 },
	{ type: HELMETS.STANDARD_FULL_CAGE_2, weight: 1 },
	{ type: HELMETS.STANDARD_FULL_CAGE_ROBOT, weight: 1 },
	{ type: HELMETS.STANDARD_HALF_CAGE_2, weight: 0.1 },
	{ type: HELMETS.STANDARD_BULLDOG, weight: 1 },
	{ type: HELMETS.AIR_XP_TWO_BAR, weight: 0.5 },
	{ type: HELMETS.AIR_XP_THREE_BAR, weight: 0.5 },
	{ type: HELMETS.AIR_XP_FULL_CAGE_1, weight: 1 },
	{ type: HELMETS.AIR_XP_HALF_CAGE_1, weight: 0.1 },
	{ type: HELMETS.AIR_XP_ROBOT_RB, weight: 0.5 },
	{ type: HELMETS.AIR_XP_KICKER, weight: 0.5 },
	{ type: HELMETS.AIR_XP_ROBOT, weight: 0.5 },
	{ type: HELMETS.AIR_XP_THREE_BAR_RB, weight: 0.5 },
	{ type: HELMETS.AIR_XP_THREE_BAR_RB_JAGGED, weight: 0.5 },
	{ type: HELMETS.AIR_XP_FULL_CAGE_2, weight: 1 },
	{ type: HELMETS.AIR_XP_FULL_CAGE_ROBOT, weight: 1 },
	{ type: HELMETS.AIR_XP_HALF_CAGE_2, weight: 0.1 },
	{ type: HELMETS.AIR_XP_BULLDOG, weight: 1 },
	{ type: HELMETS.SCHUTT_TWO_BAR, weight: 0.5 },
	{ type: HELMETS.SCHUTT_THREE_BAR, weight: 0.5 },
	{ type: HELMETS.SCHUTT_FULL_CAGE_1, weight: 1 },
	{ type: HELMETS.SCHUTT_HALF_CAGE_1, weight: 0.1 },
	{ type: HELMETS.SCHUTT_ROBOT_RB, weight: 0.5 },
	{ type: HELMETS.SCHUTT_KICKER, weight: 0.5 },
	{ type: HELMETS.SCHUTT_ROBOT, weight: 0.5 },
	{ type: HELMETS.SCHUTT_THREE_BAR_RB, weight: 0.5 },
	{ type: HELMETS.SCHUTT_THREE_BAR_RB_JAGGED, weight: 0.5 },
	{ type: HELMETS.SCHUTT_FULL_CAGE_2, weight: 1 },
	{ type: HELMETS.SCHUTT_FULL_CAGE_ROBOT, weight: 1 },
	{ type: HELMETS.SCHUTT_HALF_CAGE_2, weight: 0.1 },
	{ type: HELMETS.SCHUTT_BULLDOG, weight: 1 },
	{ type: HELMETS.DNA_DNA_1, weight: 1 },
	{ type: HELMETS.DNA_DNA_2, weight: 1 },
	{ type: HELMETS.DNA_DNA_3, weight: 1 },
	{ type: HELMETS.DNA_DNA_4, weight: 1 },
	{ type: HELMETS.DNA_DNA_5, weight: 1 },
	{ type: HELMETS.DNA_DNA_6, weight: 1 },
	{ type: HELMETS.DNA_DNA_6, weight: 1 },
	{ type: HELMETS.DNA_DNA_ROPO_SW, weight: 1 },
	{ type: HELMETS.DNA_DNA_ROPO_SW_2, weight: 1 },
	{ type: HELMETS.REVO_SPEED_SPEED_ROBOT, weight: 1 },
	{ type: HELMETS.REVO_SPEED_SPEED_ROBOT_2, weight: 0.5 },
	{ type: HELMETS.REVO_SPEED_SPEED_FULL_CAGE, weight: 1 },
	{ type: HELMETS.REVO_SPEED_SPEED_3_BAR_RB, weight: 1 },
	{ type: HELMETS.REVO_SPEED_SPEED_3_BAR_LB, weight: 1 },
	{ type: HELMETS.REVO_SPEED_SPEED_3_BAR, weight: 0.1 },
	{ type: HELMETS.ION_4D_ION_2_BAR, weight: 0.1 },
	{ type: HELMETS.ION_4D_ION_ROBOT_RB, weight: 1 },
	{ type: HELMETS.ION_4D_ION_3_BAR_RB, weight: 1 },
	{ type: HELMETS.ION_4D_ION_FULL_CAGE, weight: 1 },
	{ type: HELMETS.ION_4D_ION_FULL_CAGE_2, weight: 1 },
	{ type: HELMETS.ION_4D_ION_3_BAR, weight: 0.5 },
];

module.exports = oLinePositions;
