const NORMAL = 0;
const WRISTBAND_WHITE = 1;
const WRISTBAND_TEAM_COLOR = 3;
const DBL_WRISTBANDS_WHITE = 4;
const DBL_WRISTBANDS_TEAM_COLOR = 6;
const QB_WRISTBAND_WHITE = 7;
const QB_WRISTBAND_TEAM_COLOR = 9;
const TAPED_WRIST_LITE = 10;
const TAPED_WRIST_NORMAL = 11;
const TAPED_WRIST_MAX = 12;
const TAPED_GLOVE_HEAVY_WHITE = 13;
const TAPED_GLOVE_NORMAL_WHITE = 14;
const WRIST_BRACE = 17;

module.exports = {
	NORMAL,
	WRISTBAND_WHITE,
	WRISTBAND_TEAM_COLOR,
	DBL_WRISTBANDS_WHITE,
	DBL_WRISTBANDS_TEAM_COLOR,
	QB_WRISTBAND_WHITE,
	QB_WRISTBAND_TEAM_COLOR,
	TAPED_WRIST_LITE,
	TAPED_WRIST_NORMAL,
	TAPED_WRIST_MAX,
	TAPED_GLOVE_HEAVY_WHITE,
	TAPED_GLOVE_NORMAL_WHITE,
	WRIST_BRACE,
};
